# Generated by Django 3.2 on 2021-04-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20210418_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='university.faculty'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
